// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "rollypollie0":return img`
.........................
.........................
.........................
.........................
.........................
.........dfffff..........
........fdeeeeedf........
.......ffbeeeebeef.......
.......eeedeeebeee.......
......feeebdebdeeef......
......bdeeebedeeeeef.....
.....febdeebedeeeeef.....
.....feeebdddddbeeef.....
.....feeeeeedebfdbef.....
.....feeeeebeeedfdbf.....
......feeeebeeeebdf......
.......eeebdeeeeef.......
.......feedeeeeeef.......
........fbffeeef.........
.........ffffff..........
.........................
.........................
.........................
.........................
.........................
`;
            case "image1":
            case "rollypollie":return img`
.........................
.........................
.........................
.........................
.........................
.........dfffff..........
........fdeeeeedf........
.......ffbeeeebeef.......
.......eeedeeebeee.......
......feeebdebdeeef......
......bdeeebedeeeeef.....
.....febdeebedeeeeef.....
.....feeebdddddbeeef.....
.....feeeeeedebfdbef.....
.....feeeeebeeedfdbf.....
......feeeebeeeebdf......
.......eeebdeeeeef.......
.......feedeeeeeef.......
........fbffeeef.........
.........ffffff..........
.........................
.........................
.........................
.........................
.........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
